[package]
name = "wasm_alloc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.13.1"
thiserror = "1.0.39"

[dev-dependencies]
rand = "0.8.5"

[workspace]
members = [
  "e2e"
]
